var Count;
var SentenceCount;
var Sentence = [];
var Poem = [];

var Title;
var ButtonStart;
var ButtonOne;
var ButtonTwo;
var ButtonThree;
var ButtonFour;
var ButtonRestart;
var ButtonOthers;
var ButtonNext;
var SentenceOne;
var SentenceTwo;
var SentenceThree;
var PoemName;

var PoemIndex;
var SentenceNow;
var SentenceRandom;
var SuccessiveNumber;
var ErrorNumber;
var Answer;
var Start;
var Correct;
var Successive;
var SuccessiveMax;
var Error;
var StartIndex;
var EndIndex;
